# This file was generated by GoReleaser. DO NOT EDIT.
class Deckmaster < Formula
  desc "An application to control your Elgato Stream Deck"
  homepage "https://fribbledom.com/"
  version "0.1.0"
  bottle :unneeded
  depends_on :linux

  if OS.mac?
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/muesli/deckmaster/releases/download/v0.1.0/deckmaster_0.1.0_linux_x86_64.tar.gz"
      sha256 "b8f39f90f3342fd55d92603eb397d1f13c776ae6e74ba38e156ec1b2aece6862"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/muesli/deckmaster/releases/download/v0.1.0/deckmaster_0.1.0_linux_arm64.tar.gz"
        sha256 "18b6fc98f181a65d4cd4db9d265cd67070021994c8e94073a9b7efa32e1886aa"
      else
        url "https://github.com/muesli/deckmaster/releases/download/v0.1.0/deckmaster_0.1.0_linux_armv6.tar.gz"
        sha256 "2c62ef318e60145c304fc74c65e1552954494d072716db701ab3abceac0e5ddd"
      end
    end
  end

  def install
  end
end
