# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Duf < Formula
  desc "Disk Usage/Free Utility"
  homepage "https://fribbledom.com/"
  version "0.6.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/muesli/duf/releases/download/v0.6.0/duf_0.6.0_Darwin_x86_64.tar.gz"
    sha256 "0a84151327f5fdbebc90dc309708a0cd7da368394e358db37f6dc4a250725bac"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/muesli/duf/releases/download/v0.6.0/duf_0.6.0_linux_x86_64.tar.gz"
    sha256 "2cf2e6263dcdd4809c1a9ca2ee50ce0c228c5720a1d3ddd1cae084f8fbfe1ae1"
  end
  if OS.linux? && Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
    url "https://github.com/muesli/duf/releases/download/v0.6.0/duf_0.6.0_linux_armv6.tar.gz"
    sha256 "9805268265019cadad313106e62d1b55e585d88cbb6c00ab7173684db09fbf24"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/muesli/duf/releases/download/v0.6.0/duf_0.6.0_linux_arm64.tar.gz"
    sha256 "de978266fc8c272bec7f3b0de5e85e652c92268009ecbd829ac444edc96d3890"
  end

  def install
    bin.install "duf"
  end
end
