# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Duf < Formula
  desc "Disk Usage/Free Utility"
  homepage "https://fribbledom.com/"
  version "0.6.1"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/muesli/duf/releases/download/v0.6.1/duf_0.6.1_Darwin_x86_64.tar.gz"
    sha256 "a417ae9d3756af572964ff94a3ecb8e4bbd5ef50a75f4d092c0191c792980f91"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/muesli/duf/releases/download/v0.6.1/duf_0.6.1_Darwin_arm64.tar.gz"
    sha256 "21765dfc815a24a9b88991089b919b577096fb4cce95cb8d6625c66ea90bfdb7"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/muesli/duf/releases/download/v0.6.1/duf_0.6.1_linux_x86_64.tar.gz"
    sha256 "d2c48e5dc5c77c530677a3e43376539c7bc525c4dbbdf8db7a9adeba9c45137d"
  end
  if OS.linux? && Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
    url "https://github.com/muesli/duf/releases/download/v0.6.1/duf_0.6.1_linux_armv6.tar.gz"
    sha256 "f5bb387f47c9fbdfc720b3e9ccfb19afb581193bb22877b470ebc3e557ac83ca"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/muesli/duf/releases/download/v0.6.1/duf_0.6.1_linux_arm64.tar.gz"
    sha256 "f1d34a2b9fb7c1db3f1e32b983cdf55f52a2d5440214330b0c36b1b1bbfc4a15"
  end

  def install
    bin.install "duf"
  end
end
