# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gitty < Formula
  desc "Smart little CLI helper for git projects"
  homepage "https://fribbledom.com/"
  version "0.2.2"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/muesli/gitty/releases/download/v0.2.2/gitty_0.2.2_Darwin_x86_64.tar.gz"
      sha256 "64555f336db972bca74bd3cac99f7bae1bd063837de65118643e9121d856baa4"
    end
    if Hardware::CPU.arm?
      url "https://github.com/muesli/gitty/releases/download/v0.2.2/gitty_0.2.2_Darwin_arm64.tar.gz"
      sha256 "a28f9abe1e9d5dbefed66396d1dfff26d875317a718a74ece445e2a89dc328f5"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/muesli/gitty/releases/download/v0.2.2/gitty_0.2.2_linux_x86_64.tar.gz"
      sha256 "f3d2b3f559ca59ebbb69ad6943c4cdb6574b7d98100c2ef3371ad2231b5dfdf0"
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/muesli/gitty/releases/download/v0.2.2/gitty_0.2.2_linux_armv6.tar.gz"
      sha256 "7737d91518c50d5645e6c1108031393981264b7db7e35b760f1baa7ddb02c390"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/muesli/gitty/releases/download/v0.2.2/gitty_0.2.2_linux_arm64.tar.gz"
      sha256 "f1de5d9b108819ea5a3c0aee14aacb131272463060bb31cb0f638b8df349dfad"
    end
  end

  def install
    bin.install "gitty"
  end
end
