# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gitty < Formula
  desc "Smart little CLI helper for git projects"
  homepage "https://fribbledom.com/"
  version "0.5.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/muesli/gitty/releases/download/v0.5.0/gitty_0.5.0_Darwin_arm64.tar.gz"
      sha256 "57d93bebfd3859d695d5b67950c57262a7c479963e846be602178cf86c3b6f2a"

      def install
        bin.install "gitty"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/muesli/gitty/releases/download/v0.5.0/gitty_0.5.0_Darwin_x86_64.tar.gz"
      sha256 "8fa3623a5bd95e10254a0efe431f3a8cfe38c9a9b7ae57aae49c1de699e64aee"

      def install
        bin.install "gitty"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/muesli/gitty/releases/download/v0.5.0/gitty_0.5.0_linux_armv6.tar.gz"
      sha256 "356f63f10007e05f02d19734899ce01693b720af56424866337305b9f2b96b04"

      def install
        bin.install "gitty"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/muesli/gitty/releases/download/v0.5.0/gitty_0.5.0_linux_arm64.tar.gz"
      sha256 "9bc0b08f291766ea5bb25daff5b1849eb6b8fc40c87e0ed68cd97e1b36caf8bd"

      def install
        bin.install "gitty"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/muesli/gitty/releases/download/v0.5.0/gitty_0.5.0_linux_x86_64.tar.gz"
      sha256 "315d1b41015d9568ee029d1761c6ae23a851dd75abde749942639d54818e071e"

      def install
        bin.install "gitty"
      end
    end
  end
end
