# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Markscribe < Formula
  desc "Your personal markdown scribe with template-engine and Git(Hub) & RSS powers"
  homepage "https://fribbledom.com/"
  version "0.6.0"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/muesli/markscribe/releases/download/v0.6.0/markscribe_0.6.0_Darwin_x86_64.tar.gz"
      sha256 "470dd002bc04dc93dc88d167a5f9d9200c42a1b8fee40b89e5e2b0967f2487c9"
    end
    if Hardware::CPU.arm?
      url "https://github.com/muesli/markscribe/releases/download/v0.6.0/markscribe_0.6.0_Darwin_arm64.tar.gz"
      sha256 "d13e656a67b879007b4019a4b5d0f406cb989ba4ce1d82797f7a3fc851a10488"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/muesli/markscribe/releases/download/v0.6.0/markscribe_0.6.0_linux_x86_64.tar.gz"
      sha256 "695ebc6ab3a64dc34c9de5cfed2676154c726ce0fb53cb3e6b758e4333015677"
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/muesli/markscribe/releases/download/v0.6.0/markscribe_0.6.0_linux_armv6.tar.gz"
      sha256 "ef285359cd7be354425846f6d50d43c04afe66db80643ecf9e4048f7b3629458"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/muesli/markscribe/releases/download/v0.6.0/markscribe_0.6.0_linux_arm64.tar.gz"
      sha256 "e330e3fec1580c3c9a6aa792dc68f363b6da20499be276f469477cd580a564a4"
    end
  end

  def install
    bin.install "markscribe"
  end
end
