# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Markscribe < Formula
  desc "Your personal markdown scribe with template-engine and Git(Hub) & RSS powers"
  homepage "https://fribbledom.com/"
  version "0.4.0"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/muesli/markscribe/releases/download/v0.4.0/markscribe_0.4.0_Darwin_x86_64.tar.gz"
      sha256 "5adafea97df5b787d4be357a87a736027158ffe512e4eb07505da8c6ca381fa4"
    end
    if Hardware::CPU.arm?
      url "https://github.com/muesli/markscribe/releases/download/v0.4.0/markscribe_0.4.0_Darwin_arm64.tar.gz"
      sha256 "1908d358a74ba10ec4d764f487a0fbce8a3fafabd1aff2ca48b716a2f7eb7f11"
    end

    depends_on arch: [:x86_64, :aarch64]
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/muesli/markscribe/releases/download/v0.4.0/markscribe_0.4.0_linux_x86_64.tar.gz"
      sha256 "e0198b56a21273f8c195f9fcb346b5bd80b92c9028c95e7a13b02095729acbe4"
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/muesli/markscribe/releases/download/v0.4.0/markscribe_0.4.0_linux_armv6.tar.gz"
      sha256 "bcca1bf60173e0277fb0b7a316266070d92f4d50cf928636f05daaad1e3b5202"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/muesli/markscribe/releases/download/v0.4.0/markscribe_0.4.0_linux_arm64.tar.gz"
      sha256 "0958834f5432f5c5057f7fdd9606ab4aefa9eed9285ac3dc3fbbc2f613852dc7"
    end

    depends_on arch: [:x86_64, :aarch64, :arm]
  end

  def install
    bin.install "markscribe"
  end
end
