# This file was generated by GoReleaser. DO NOT EDIT.
class Mastotool < Formula
  desc "Mastodon CLI tool & statistics generator"
  homepage "https://fribbledom.com/"
  version "0.2.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/muesli/mastotool/releases/download/v0.2.1/mastotool_0.2.1_Darwin_x86_64.tar.gz"
    sha256 "2fa41c3c72cd6a3fa392609629d89614b47c0895185c9203b497552bd694476d"
  elsif OS.linux?
  end

  def install
    bin.install "mastotool"
  end
end
