# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ObsCli < Formula
  desc "OBS-cli is a command-line remote control for OBS"
  homepage "https://fribbledom.com/"
  version "0.3.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/muesli/obs-cli/releases/download/v0.3.0/obs-cli_0.3.0_Darwin_arm64.tar.gz"
      sha256 "6cd626e4aeaab3b589afd62f61807af4e8778791527561d65c4b90cd8df37886"

      def install
        bin.install "obs-cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/muesli/obs-cli/releases/download/v0.3.0/obs-cli_0.3.0_Darwin_x86_64.tar.gz"
      sha256 "b9deca683df00a5d0428bbc8247f9b85c88f90b2e8c1b1af07acb14b17c902a0"

      def install
        bin.install "obs-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/muesli/obs-cli/releases/download/v0.3.0/obs-cli_0.3.0_linux_armv6.tar.gz"
      sha256 "f9045ad4aba63efb273ce8dec58601e369563aa18690d5498aa1d22534dcfaa9"

      def install
        bin.install "obs-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/muesli/obs-cli/releases/download/v0.3.0/obs-cli_0.3.0_linux_arm64.tar.gz"
      sha256 "009e4cccc14fb9f785834c12c664702c02bc3ca4fba1acd2beca77d991a25766"

      def install
        bin.install "obs-cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/muesli/obs-cli/releases/download/v0.3.0/obs-cli_0.3.0_linux_x86_64.tar.gz"
      sha256 "9b354cbfc1ebd4af8beb8649c99a81cecdb8f8c9c2bf7d2735a40a19c77aef40"

      def install
        bin.install "obs-cli"
      end
    end
  end
end
