# This file was generated by GoReleaser. DO NOT EDIT.
class ObsCli < Formula
  desc "OBS-cli is a command-line remote control for OBS"
  homepage "https://fribbledom.com/"
  version "0.1.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/muesli/obs-cli/releases/download/v0.1.0/obs-cli_0.1.0_Darwin_x86_64.tar.gz"
    sha256 "a730d397154281bbb0c7f7f4b0643c2eda0a86fd6cc8887ac50cb933693b1d0b"
  elsif OS.linux?
  end

  def install
    bin.install "obs-cli"
  end
end
