# This file was generated by GoReleaser. DO NOT EDIT.
class Prism < Formula
  desc "Disk Usage/Free Utility"
  homepage "https://fribbledom.com/"
  version "0.1.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/muesli/prism/releases/download/v0.1.0/prism_0.1.0_Darwin_x86_64.tar.gz"
    sha256 "bad49c43cd1a6c21bc7bb5d38e0470c60e7ac197d0e7437238b2693bccd6813d"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/muesli/prism/releases/download/v0.1.0/prism_0.1.0_linux_x86_64.tar.gz"
      sha256 "e0b25dd65bf1bbc80a18e9be3f95fe4ad633d373f75321ba86731d7c15d4018b"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/muesli/prism/releases/download/v0.1.0/prism_0.1.0_linux_arm64.tar.gz"
        sha256 "a4d30463b659569ce35a3a0e635df7c2850b6f353efa943b2a99930593236d74"
      else
        url "https://github.com/muesli/prism/releases/download/v0.1.0/prism_0.1.0_linux_armv6.tar.gz"
        sha256 "e43a66f5545ae7eae8a053d2799ada789d6a627948d8548585f4e9c0f3f99ba5"
      end
    end
  end

  def install
    bin.install "prism"
  end
end
